generate emoji & unicode data scripts: small change in error message

diff --git a/dot-local/bin/generate-emoji-data b/dot-local/bin/generate-emoji-data
--- a/dot-local/bin/generate-emoji-data
+++ b/dot-local/bin/generate-emoji-data
@@ -7,7 +7,7 @@ fileGeneratedEmojiData="$HOME/.local/share/unicode/EmojiGeneratedData.txt"
 fileEmojiData="/usr/share/unicode/emoji/emoji-test.txt"
 
 if [[ ! -f $fileEmojiData ]]; then
-    echo "Aborting, Emoji data file not found ($fileEmojiData)" >&2
+    echo "Aborting, Emoji data file '$fileEmojiData' not found" >&2
     exit 1
 fi
 
diff --git a/dot-local/bin/generate-unicode-data b/dot-local/bin/generate-unicode-data
--- a/dot-local/bin/generate-unicode-data
+++ b/dot-local/bin/generate-unicode-data
@@ -7,7 +7,7 @@ fileGeneratedUnicodeData="$HOME/.local/share/unicode/UnicodeGeneratedData.txt"
 fileUnicodeData="/usr/share/unicode/UnicodeData.txt"
 
 if [[ ! -f $fileUnicodeData ]]; then
-    echo "Aborting, Unicode data file not found ($fileUnicodeData)" >&2
+    echo "Aborting, Unicode data file '$fileUnicodeData' not found" >&2
     exit 1
 fi
 
